spring:
    h2:
        console:
            enabled: true
    datasource:
#        url: jdbc:h2:tcp://localhost/~/Seviper
        jdbc-url: jdbc:h2:mem:testSeviper
        username: admin
        password: Asdf963.
        driver-class-name: org.h2.Driver
    data:
        neo4j:
            uri: file:/var/tmp/neo4j.db
            username: admin
            password: Asdf963.

server:
   port: 8090
   contextPath: /H

hibernate:
    dialect: default

h:
   config:
      jwtSecret: UmFuZG9tIGNoYXJhY3RlciBjb3VudCB0b29sIHNvIHRoZSBzZWNyZXQga2V5IGl0cyBhdCBsZWFzdCAyNTYgY2hhcmFjdGVycyB0byBlbnN1cmUgbWF4aW11bSBzZWN1cml0eQ==
      jwtExpiration: 1